### ISSUE TITLE
Actor resets to initial values and can not be edited after editing item properties.

### ISSUE THREAD

**Issue by Glyph-K** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#235]
After editing an equipped item to add a new attribute for a braced autofire mode the actor's sheet has been reset and can not be edited (ex. adding a species).

Image of the attribute on another actor:
 ![autobraced](https://user-images.githubusercontent.com/107079698/172987347-e9808adb-4769-4f8e-b931-3113ea4ced51.PNG)

`foundry.js:319 TypeError: Cannot read properties of null (reading 'key')
    at attribute-helper.js:226:82
    at Array.filter (<anonymous>)
    at extractModeAttributes (attribute-helper.js:226:62)
    at getInheritableAttribute (attribute-helper.js:182:29)
    at SWSEItem.getResolvedSizeIndex (item.js:135:39)
    at SWSEItem.addSizeAdjustmentPrefix (item.js:121:38)
    at SWSEItem.buildItemName (item.js:89:26)
    at get name [as name] (item.js:79:25)
    at SWSEItem.prepareData (item.js:38:35)
    at SWSEActor.prepareEmbeddedDocuments (foundry.js:10794:11)`

[fvtt-Actor-test.zip](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/files/8875600/fvtt-Actor-test.zip)

**Comment by LeKopic** [comment]
Hm, interesting. Your actor seems to be bugged for me too when importing, but I couldn't replicate it on my own. 
Are you using the latest version (0.5.29)?

**Comment by Glyph-K** [comment]
@LeKopic I haven't been able to replicate either. I am on 0.5.29.
