### ISSUE TITLE
Issues with the Systems tab on Vehicles

### ISSUE THREAD

**Issue by xenogray** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#376]
Hello,

I encounter quite some issues while trying to change a vehicle's systems.

> Can't be moved out of "Uninstalled"
> Can't delete any system

In my case, I went by two different approaches :
-> Creating a base vehicle and apply a slightly modified (values only) Light Freighter template then changing systems makes the sheet unopenable after closing it with this error (+ random values all over the place, like Dex bonus at -38) : 

TypeError: An error occurred while rendering SWSEActorSheet 127. Cannot read properties of undefined (reading 'system')
[Detected 1 package: system:swse]
    at Attack.isMelee (attack.js:270:25)
    at Attack.getDynamicModes (attack.js:748:18)
    at get modes [as modes] (attack.js:632:35)
    at lookupProperty (handlebars.min.js:27:16153)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:51:192)
    at Object.h [as inverse] (handlebars.min.js:27:17870)
    at Object.<anonymous> (handlebars.min.js:27:10101)
    at Object.<anonymous> (handlebars.min.js:27:10278)
    at Object.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:10:54)
    at Object.h [as fn] (handlebars.min.js:27:17870)
    at Object.<anonymous> (handlebars.min.js:27:10117)
    at Object.c (handlebars.min.js:27:19853)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:10:50)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at Object.h (handlebars.min.js:27:18738)
    at Object.c [as invokePartial] (handlebars.min.js:27:15036)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:10:31)
    at Object.h [as fn] (handlebars.min.js:27:17870)
    at Attack.<anonymous> (handlebars.min.js:27:10117)
    at Attack.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:10:50)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at Object.<anonymous> (handlebars.min.js:27:7289)
    at Object.c (handlebars.min.js:27:19853)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:12:49)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at Object.h (handlebars.min.js:27:18738)
    at Object.c [as invokePartial] (handlebars.min.js:27:15036)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:30:28)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at renderTemplate (foundry.js:6948:10)
    at async SWSEActorSheet._renderInner (foundry.js:5271:16)
    at async SWSEActorSheet._renderInner (foundry.js:5833:18)
    at async SWSEActorSheet._render (foundry.js:5114:19)
    at async SWSEActorSheet._render (foundry.js:5822:5)
    
EDIT : That seems to appear with  the Light Concussion Missile Launcher and the Light Concussion Missile when you try to assign them to a Pilot or Gunner station
    
-> Starting with a base Ghtroc 720 Freighter and modifying its systems seems to break things. For example, I tried to add 1 more Medium Laser Cannon : that made the base attack disappear. Can't add another Gunner also
Added a Class 1 Hyperdrive to replace the Class 2, that seems to work but since I couldn't delete the Class 2 it's a bit confusing on how he took that into account.

EDIT2 : It seems the sub-systems are not registering
<img width="392" alt="image" src="https://user-images.githubusercontent.com/127744116/229226808-419a775a-7f33-4a46-9400-38e093a4062a.png">

[fvtt-Actor-ghtroc-720-freighter.zip](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/files/11126422/fvtt-Actor-ghtroc-720-freighter.zip)

Added the actual entity if that helps

**Comment by kypvalanx** [comment]
figured out the subtype problem.  the key in the map where that is looked up is the type "vehicleSystem".  i have a tendancy to clean inputs and made it do a toLowercase before doing lookup. so it always fails

**Comment by kypvalanx** [comment]
new changes to this system have covered every issue in this... well issue.
